# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.

#### Import NumPy (as np)

In [1]:
import numpy as np

#### Set the seed to 0

In [2]:
np.random.seed(0)

#### Create an array of 10 zeros 

In [7]:
ar_zero = np.zeros(10)
ar_zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [8]:
ar_one = np.ones(10)
ar_one

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [10]:
ar_five = np.full(10, 5.0)
ar_five

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50 (in order)

In [16]:
ar_int = np.array(range(10,51))
ar_int

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [18]:
ar_even = np.array(range(10,51,2))
ar_even

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 5x5 matrix with values ranging from 0 to 8

In [19]:
ar_rand = np.random.randint(0, 8, (5, 5))
ar_rand

array([[4, 7, 5, 0, 3],
       [3, 3, 7, 1, 3],
       [5, 2, 4, 7, 6],
       [0, 0, 4, 2, 1],
       [6, 7, 7, 6, 0]])

#### Create a 3x3 identity matrix

In [20]:
ar_identity = np.identity(3)
ar_identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [29]:
np.random.uniform()

0.8360787635373775

#### Use NumPy to generate a 5x5 matrix of 25 random numbers sampled from a standard normal distribution

In [31]:
ar_normal = np.random.normal(size = (5, 5))
ar_normal

array([[ 1.2206081 , -1.33949555,  0.42837337, -0.12346315,  1.41437719],
       [-0.12405066,  2.00815709,  0.22988654,  0.60489373,  1.62715982],
       [ 1.59456053,  0.23043417, -0.06491034, -0.96898025,  0.59124281],
       [-0.7827755 , -0.44423283, -0.34518616, -0.88180055, -0.44265324],
       [-0.5409163 , -1.32322737, -0.11279892,  0.90734594,  0.81526991]])

#### Create the following matrix (hint: use `linspace` with `reshape`):

Expected result:
```python
array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])
```

In [33]:
ar_ten = np.linspace(0.01, 1, 100).reshape((10,10))
ar_ten

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [36]:
ar_sp = np.linspace(0, 1, 20)
ar_sp

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [37]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [1]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW

```python 
[Output]:
array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])
```

In [39]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [2]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW

```python 
[Output]:
20
```

In [42]:
mat[-2,-1]

20

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW

```python 
[Output]:
array([[ 2],
       [ 7],
       [12]])

```

In [50]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [3]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW

```python 
[Output]:
array([21, 22, 23, 24, 25])

```

In [52]:
mat[-1]

array([21, 22, 23, 24, 25])

In [4]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW

```python 
[Output]:
array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```

In [53]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Conditional Indexing (AKA fancy indexing)

In [120]:
import numpy as np
np.random.seed(0)

In [121]:
mat = np.random.randint(-5, 50, size=[5,5])
mat

array([[39, 42, 48, -5, -2],
       [-2, 34,  4, 14, 16],
       [45, 31, 18,  1, 19],
       [19,  7, -4, 33, 34],
       [18, 41, 19, 12, 32]])

#### Select all elements that are greater than 5.

Expected result:
```python
array([39, 42, 48, 34, 14, 16, 45, 31, 18, 19, 19,  7, 33, 34, 18, 41, 19,
       12, 32])
```

In [122]:
mat[mat>5]

array([39, 42, 48, 34, 14, 16, 45, 31, 18, 19, 19,  7, 33, 34, 18, 41, 19,
       12, 32])

#### Select all rows where the first element is less than or equal to 20.

Expected result:
```python
array([[-2, 34,  4, 14, 16],
       [19,  7, -4, 33, 34],
       [18, 41, 19, 12, 32]])
```

In [123]:
mat[mat[:,0] <= 20, :]

array([[-2, 34,  4, 14, 16],
       [19,  7, -4, 33, 34],
       [18, 41, 19, 12, 32]])

### Replace all negative elements with 0.

Expected result:
```python
array([[39, 42, 48,  0,  0],
       [ 0, 34,  4, 14, 16],
       [45, 31, 18,  1, 19],
       [19,  7,  0, 33, 34],
       [18, 41, 19, 12, 32]])
```

In [124]:
mat[mat < 0] = 0
mat

array([[39, 42, 48,  0,  0],
       [ 0, 34,  4, 14, 16],
       [45, 31, 18,  1, 19],
       [19,  7,  0, 33, 34],
       [18, 41, 19, 12, 32]])

### Calculate the sum of all elements that are less than or equal to 5.

Expected result: `5`

In [125]:
np.sum(mat, where = mat <= 5)

5

### Calculate the mean of all elements in the last column.

Expected result: `20.2`

In [126]:
mat[:,-1].mean()

20.2

#### Count the number of elements that are not equal to 0.

Expected result: `21`

In [127]:
len(mat[mat != 0])

21

#### Replace all elements equal to the maximum value of the matrix with 0.

Expected result:
```python
array([[39, 42,  0,  0,  0],
       [ 0, 34,  4, 14, 16],
       [45, 31, 18,  1, 19],
       [19,  7,  0, 33, 34],
       [18, 41, 19, 12, 32]])
```

In [128]:
mat[mat == mat.max()] = 0
mat

array([[39, 42,  0,  0,  0],
       [ 0, 34,  4, 14, 16],
       [45, 31, 18,  1, 19],
       [19,  7,  0, 33, 34],
       [18, 41, 19, 12, 32]])

### Math on rows and columns

#### Add 5 to a all mat elements

In [129]:
mat = mat + 5
mat

array([[44, 47,  5,  5,  5],
       [ 5, 39,  9, 19, 21],
       [50, 36, 23,  6, 24],
       [24, 12,  5, 38, 39],
       [23, 46, 24, 17, 37]])

#### Get the sum of all the values in mat

In [130]:
mat.sum()

603

#### Get the standard deviation of the values in mat

In [131]:
mat.std()

15.007518115931095

#### Get the sum of all the columns in mat

In [134]:
mat.sum(axis = 0)

array([146, 180,  66,  85, 126])

#### Get the sum of all the rows in mat

In [135]:
mat.sum(axis = 1)

array([106,  93, 139, 118, 147])

# Great Job!